version: '3.8'

services: 
  postgresSQLDatabase:
      image: "postgres"
      volumes: 
       - postgresVolume:/var/lib/postgresql/data/
      restart: no
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: kosev
      ports: 
       - 5432:5432
volumes:
  postgresVolume:
      external: false